safe:        false
port:        4000

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    true
permalink:   /:year/:month/:title

title: Rocket Manufacturing
description: MME Capstone at Portland State University in cooperation with the Portland State Aerospace Society.

exclude: [drafts,README.md,Makefile,make_index.py,scripts]
